name: gamelobby
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  get: ^4.7.2

  window_manager: ^0.4.3
  audioplayers: ^6.2.0
  flutter_cube: ^0.1.1
  signalr_netcore: ^1.4.1

  url_launcher: ^6.2.5
  cached_network_image: ^3.4.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/banners/
    - assets/images/character/
    - assets/images/logos/
    - assets/images/wallpapers/
    - assets/images/keyboard/
    - assets/images/story/
    - assets/sounds/
    - assets/sounds/musics/
    - assets/videos/
    - assets/obj/
    - assets/obj/Ghost.obj
    - assets/obj/Ghost.mtl
    - assets/obj/Ghost2.obj
    - assets/obj/Ghost2.mtl